#### Bag Of Words

###### Bag of Words (BOW) is a text feature extraction technique in NLP.
###### It converts text into numerical vectors.
###### It creates a vocabulary of unique words from the dataset.
###### Each sentence/document is represented using word frequency counts.
###### BOW does not consider grammar, context, or word order.
###### Commonly used in text classification and sentiment analysis.

In [7]:
corpus = """
Artificial Intelligence and Natural Language Processing are rapidly transforming the 
modern technology landscape. Machine learning models are now capable of understanding 
human language, generating meaningful responses, translating text between languages, and even 
writing computer programs. One of the fundamental tasks in NLP is converting textual data into 
numerical form so that machine learning algorithms can process it efficiently. Traditional techniques 
such as One Hot Encoding, Bag of Words, and TF-IDF are widely used for feature extraction in text analysis. 
The Bag of Words model represents text by counting the occurrence of words in a document without
considering grammar or word order. although simple, BOW is extremely useful for understanding 
important words appear in a dataset. Modern NLP systems go beyond these traditional 
by using embeddings and transformer-based architectures that capture semantic meaning
and contextual relationships between words. Technologies such as neural networks, attention 
mechanisms, and large language models have significantly improved the capabilities of AI systems
in applications like chatbots, recommendation systems, sentiment analysis, document summarization, 
and information retrieval. Ās the field of Generative AI continues to evolve, understanding foundational 
concepts like tokenization, stop word removal, stemming, lemmatization, and feature extraction 
becomes essential for anyone learning NLP and GenAI engineering.

"""

##### text preprocessing 

In [8]:
### Required before any feature extraction / vectorization method

In [9]:
## removing specail chars 
import re 
corpus = re.sub('[^a-zA-Z]', ' ', corpus)
corpus

' Artificial Intelligence and Natural Language Processing are rapidly transforming the  modern technology landscape  Machine learning models are now capable of understanding  human language  generating meaningful responses  translating text between languages  and even  writing computer programs  One of the fundamental tasks in NLP is converting textual data into  numerical form so that machine learning algorithms can process it efficiently  Traditional techniques  such as One Hot Encoding  Bag of Words  and TF IDF are widely used for feature extraction in text analysis   The Bag of Words model represents text by counting the occurrence of words in a document without considering grammar or word order  although simple  BOW is extremely useful for understanding  important words appear in a dataset  Modern NLP systems go beyond these traditional  by using embeddings and transformer based architectures that capture semantic meaning and contextual relationships between words  Technologies su

In [10]:
## lowering the case
corpus = corpus.lower()

In [15]:
## apply stopwords
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
sw = stopwords.words('english')

words = word_tokenize(corpus)

words = [word for word in words if word not in sw]

corpus = ' '.join(words)

print(corpus)

artificial intelligence natural language processing rapidly transforming modern technology landscape machine learning models capable understanding human language generating meaningful responses translating text languages even writing computer programs one fundamental tasks nlp converting textual data numerical form machine learning algorithms process efficiently traditional techniques one hot encoding bag words tf idf widely used feature extraction text analysis bag words model represents text counting occurrence words document without considering grammar word order although simple bow extremely useful understanding important words appear dataset modern nlp systems go beyond traditional using embeddings transformer based architectures capture semantic meaning contextual relationships words technologies neural networks attention mechanisms large language models significantly improved capabilities ai systems applications like chatbots recommendation systems sentiment analysis document su

##### Implement BOW

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [20]:
x = cv.fit_transform(corpus.split()).toarray()

In [21]:
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [22]:
cv.vocabulary_

{'artificial': 8,
 'intelligence': 54,
 'natural': 69,
 'language': 56,
 'processing': 78,
 'rapidly': 80,
 'transforming': 105,
 'modern': 68,
 'technology': 98,
 'landscape': 55,
 'machine': 62,
 'learning': 59,
 'models': 67,
 'capable': 16,
 'understanding': 107,
 'human': 49,
 'generating': 44,
 'meaningful': 64,
 'responses': 85,
 'translating': 106,
 'text': 99,
 'languages': 57,
 'even': 34,
 'writing': 115,
 'computer': 19,
 'programs': 79,
 'one': 75,
 'fundamental': 42,
 'tasks': 95,
 'nlp': 72,
 'converting': 24,
 'textual': 100,
 'data': 26,
 'numerical': 73,
 'form': 40,
 'algorithms': 1,
 'process': 77,
 'efficiently': 29,
 'traditional': 103,
 'techniques': 96,
 'hot': 48,
 'encoding': 31,
 'bag': 10,
 'words': 114,
 'tf': 101,
 'idf': 50,
 'widely': 111,
 'used': 108,
 'feature': 38,
 'extraction': 36,
 'analysis': 3,
 'model': 66,
 'represents': 84,
 'counting': 25,
 'occurrence': 74,
 'document': 28,
 'without': 112,
 'considering': 21,
 'grammar': 47,
 'word': 113,


In [31]:
cv1 = CountVectorizer(max_features=50)

In [32]:
cv1.fit_transform(corpus.split()).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(145, 50))

In [33]:
cv1.vocabulary_

{'artificial': np.int64(7),
 'language': np.int64(36),
 'modern': np.int64(41),
 'machine': np.int64(39),
 'learning': np.int64(37),
 'models': np.int64(40),
 'capable': np.int64(10),
 'understanding': np.int64(47),
 'text': np.int64(45),
 'even': np.int64(24),
 'one': np.int64(43),
 'fundamental': np.int64(32),
 'nlp': np.int64(42),
 'data': np.int64(16),
 'form': np.int64(30),
 'algorithms': np.int64(1),
 'efficiently': np.int64(19),
 'traditional': np.int64(46),
 'encoding': np.int64(21),
 'bag': np.int64(8),
 'words': np.int64(49),
 'feature': np.int64(28),
 'extraction': np.int64(26),
 'analysis': np.int64(2),
 'counting': np.int64(15),
 'document': np.int64(18),
 'considering': np.int64(14),
 'grammar': np.int64(35),
 'word': np.int64(48),
 'extremely': np.int64(27),
 'appear': np.int64(4),
 'dataset': np.int64(17),
 'systems': np.int64(44),
 'go': np.int64(34),
 'embeddings': np.int64(20),
 'architectures': np.int64(6),
 'capture': np.int64(11),
 'capabilities': np.int64(9),
 'a

##### N GRAMS

###### Helps in capturing the sementics information between the words 

In [ ]:
## to understand this, we should Have list of sentences, not words

In [46]:
corpus = """
Artificial Intelligence and Natural Language Processing are rapidly transforming the 
modern technology landscape. Machine learning models are now capable of understanding 
human language, generating meaningful responses, translating text between languages, and even 
writing computer programs. One of the fundamental tasks in NLP is converting textual data into 
numerical form so that machine learning algorithms can process it efficiently. Traditional techniques 
such as One Hot Encoding, Bag of Words, and TF-IDF are widely used for feature extraction in text analysis. 
The Bag of Words model represents text by counting the occurrence of words in a document without
considering grammar or word order. although simple, BOW is extremely useful for understanding 
important words appear in a dataset. Modern NLP systems go beyond these traditional 
by using embeddings and transformer-based architectures that capture semantic meaning
and contextual relationships between words. Technologies such as neural networks, attention 
mechanisms, and large language models have significantly improved the capabilities of AI systems
in applications like chatbots, recommendation systems, sentiment analysis, document summarization, 
and information retrieval. Ās the field of Generative AI continues to evolve, understanding foundational 
concepts like tokenization, stop word removal, stemming, lemmatization, and feature extraction 
becomes essential for anyone learning NLP and GenAI engineering.

"""

In [47]:
corpus = corpus.lower()
corpus = corpus.split('.')
print(corpus)

['\nartificial intelligence and natural language processing are rapidly transforming the \nmodern technology landscape', ' machine learning models are now capable of understanding \nhuman language, generating meaningful responses, translating text between languages, and even \nwriting computer programs', ' one of the fundamental tasks in nlp is converting textual data into \nnumerical form so that machine learning algorithms can process it efficiently', ' traditional techniques \nsuch as one hot encoding, bag of words, and tf-idf are widely used for feature extraction in text analysis', ' \nthe bag of words model represents text by counting the occurrence of words in a document without\nconsidering grammar or word order', ' although simple, bow is extremely useful for understanding \nimportant words appear in a dataset', ' modern nlp systems go beyond these traditional \nby using embeddings and transformer-based architectures that capture semantic meaning\nand contextual relationships 

In [49]:
for i in range(len(corpus)):
    sent = corpus[i].strip()
    sent = [word for word in sent.split() if word not in sw]
    sent = [re.sub('[^a-zA-Z]', " ", word) for word in sent] 
    sent = ' '.join(sent)
    corpus[i] = sent

In [50]:
corpus

['artificial intelligence natural language processing rapidly transforming modern technology landscape',
 'machine learning models capable understanding human language  generating meaningful responses  translating text languages  even writing computer programs',
 'one fundamental tasks nlp converting textual data numerical form machine learning algorithms process efficiently',
 'traditional techniques one hot encoding  bag words  tf idf widely used feature extraction text analysis',
 'bag words model represents text counting occurrence words document without considering grammar word order',
 'although simple  bow extremely useful understanding important words appear dataset',
 'modern nlp systems go beyond traditional using embeddings transformer based architectures capture semantic meaning contextual relationships words',
 'technologies neural networks  attention mechanisms  large language models significantly improved capabilities ai systems applications like chatbots  recommendation

In [51]:
cv2 = CountVectorizer(max_features=70, ngram_range=(2,2))

In [52]:
x2 = cv2.fit_transform(corpus)
cv2.vocabulary_

{'artificial intelligence': np.int64(9),
 'intelligence natural': np.int64(54),
 'language processing': np.int64(57),
 'machine learning': np.int64(66),
 'learning models': np.int64(61),
 'capable understanding': np.int64(17),
 'human language': np.int64(49),
 'language generating': np.int64(55),
 'generating meaningful': np.int64(44),
 'meaningful responses': np.int64(68),
 'languages even': np.int64(58),
 'even writing': np.int64(33),
 'computer programs': np.int64(20),
 'fundamental tasks': np.int64(42),
 'converting textual': np.int64(25),
 'data numerical': np.int64(27),
 'form machine': np.int64(40),
 'learning algorithms': np.int64(60),
 'algorithms process': np.int64(2),
 'hot encoding': np.int64(48),
 'encoding bag': np.int64(31),
 'bag words': np.int64(11),
 'idf widely': np.int64(50),
 'feature extraction': np.int64(38),
 'extraction text': np.int64(36),
 'counting occurrence': np.int64(26),
 'document without': np.int64(29),
 'considering grammar': np.int64(22),
 'grammar w

In [53]:
cv3 = CountVectorizer(max_features=50, ngram_range=(3,3))

In [54]:
cv3.fit_transform(corpus)
cv3.vocabulary_

{'artificial intelligence natural': np.int64(8),
 'capable understanding human': np.int64(17),
 'human language generating': np.int64(48),
 'generating meaningful responses': np.int64(43),
 'even writing computer': np.int64(32),
 'fundamental tasks nlp': np.int64(42),
 'converting textual data': np.int64(24),
 'data numerical form': np.int64(26),
 'form machine learning': np.int64(40),
 'algorithms process efficiently': np.int64(2),
 'hot encoding bag': np.int64(47),
 'encoding bag words': np.int64(30),
 'bag words tf': np.int64(11),
 'idf widely used': np.int64(49),
 'feature extraction text': np.int64(38),
 'extraction text analysis': np.int64(35),
 'bag words model': np.int64(10),
 'counting occurrence words': np.int64(25),
 'document without considering': np.int64(28),
 'considering grammar word': np.int64(21),
 'grammar word order': np.int64(46),
 'although simple bow': np.int64(3),
 'bow extremely useful': np.int64(15),
 'extremely useful understanding': np.int64(36),
 'go beyond